#index:
#    path: /
#    controller: App\Controller\DefaultController::index
entity_route:
  path: /product/{nazwa}-{cena}
  controller: App\Controller\ProductController::createProduct
  defaults:
    nazwa: ""
    cena: 10